### PR TITLE
add openvz support for new ctop version

### PR DESCRIPTION
**Pull request by mrqwer88**
New request instead of https://github.com/yadutaf/ctop/pull/10 .

How I see I cannot work correct with **collect_ensure_common()** with openvz.
I move memory statistic to down and skip it on openvz, if if have not tasks.
In this version it work on node with https://github.com/yadutaf/ctop/issues/9, how I see.

Added key 'c' like checkpoint(it same that suspend in openvz, but not see like "stop") for openvz containers.

Other minor fixes for previos ugly moments like get_user_beacounts('root').

### CODE REVIEW

File: cgroup_top.py [hunk 1]
```diff
@@ -300,18 +306,23 @@ def collect_ensure_common(data, cgroup):
...
+def get_user_beacounts():
+    '''
+    get memory stats(via privvmpages) from vzlist output to openvz containers
+    '''
+    prefix = []
+    if os.getuid() != 0:
+       prefix = ['sudo']
+
+    command = prefix + ['vzlist', '-o', 'ctid,privvmpages,privvmpages.l', '-H']
+    return os.popen(" ".join(command)).readlines()
```
Comment (yadutaf) [inline cgroup_top.py]:
```
return subprocess.check_output(command).split('\n')
```

**Comment by yadutaf** [comment]
One last fix and we're good to go.

```
git commit -sa --amend
git push -f
```

Thanks.

File: cgroup_top.py (hunk 1 above)
Comment (mrqwer88) [inline cgroup_top.py]: It broken work with Python 2.6.
check_output was introduced in python 2.7 so won't work for < 2.7 - https://docs.python.org/2/library/subprocess.html#subprocess.check_output (new in 2.7)
With Python 2.6.6 (by default in Centos 6) - 

```
Traceback (most recent call last):
  File "./cgroup_top.py", line 901, in <module>
    main()
  File "./cgroup_top.py", line 875, in main
    collect(measures)
  File "./cgroup_top.py", line 367, in collect
    user_beancounters = get_user_beacounts()
  File "./cgroup_top.py", line 318, in get_user_beacounts
    return subprocess.check_output(command).split('\n')
AttributeError: 'module' object has no attribute 'check_output'
```

Comment (mrqwer88) [inline cgroup_top.py]: Try to rewrite it with subprocess.Popen and stdout=PIPE ?

Comment (yadutaf) [inline cgroup_top.py]: Yep. This may help: https://docs.python.org/2.6/library/subprocess.html#replacing-os-popen-os-popen2-os-popen3 but using the command list directly without `shell=True`. Thanks.

Comment (mrqwer88) [inline cgroup_top.py]: OK - rewrite it with subprocess.Popen and shell=False.

**Comment by yadutaf** [comment]
Merged. Thanks!
